# DH-150-Assignments
# Assignment02:Pilot Usability Testing
## Introduction–The Purpose of UT:
Through this Usability Testing, I hope to get insights into my user habits and understand our mutual pain points. The purpose of this testing is to assess how easy user interfaces are to use. It also offers different perspectives and methods to interact with a website that the designer of said website or research study may not be familiar with. Usability testing analyzes the extent to which users achieve the metrics of effectiveness, efficiency, satisfaction, learnability, memorability, usefulness, utility, usability, and accessibility in a specific context of use. Overall, this type of testing looks at a product's usability. I specifically am testing the three heuristic components of Flexibility & Efficiency of Use, Recognition Rather than Recall, and Aesthetic and Minimal Design. I am going to have my user give feedback on the Menu section, the layout of the website, the about section of the website, whether or not there is a frequently asked questions section to gauge recognition rather than recall, and lastly have my participant try and find a specific bit of information using the search bar.

## Link to Online Survey:
https://docs.google.com/forms/d/e/1FAIpQLSejgwyMTbnRU5YuiXeWg4lLJH6jRjmSXDY8xNaai19FXt69Og/viewform

## Link to Pilot Video:
https://drive.google.com/file/d/1FwwyCwPochkkuSgcOuLxrxUueEz6SMaS/view?usp=sharing

## What was Learned
I found this process to be incredibly insightful in terms of discovering new ways to improve my survey, the different ways other individuals can interact with the website, and how the usability of this website was lacking. What aspect of the usability testing that didn’t go well was that I had to interject into my user’s testing because there were so many complications, such as the fact that he skipped one of the initial questions on the survey so I had to remind him to read it so the rest of the survey would make sense. Also, since the testee was my dad, I found it difficult to note show emotion or “play dumb” while I was administering the test. That being said, it seemed as though the rest of the usability testing went well and my user even showed me innovative new ways to solve problems on the website that I wouldn’t have thought about. One major issue I found with the website was the lack of filter when using the search tab but he simply listed all his search terms and he was able to easily use the site. With more user testing, I hope to see if the masses think more like my dad or more like me-- to gauge how much of an issue the search feature truly is. Overall, I want to refine my Usability Test to be more concise while expanding my user pool to get more representative feedback on the usability of this website. 
